# GB0060

## Graph-Break Type
*Short name describing what triggered the graph break*
Failed to trace unittest method

## Context
*Values or code snippet captured at the break point*
function: unittest.TestCase.{name}

## Explanation
*Why this specific graph break happened*
Dynamo does not know how to trace unittest method `{name}` 

## Hints
*Suggestions for fixing or working around the break*
- Avoid calling `TestCase.{name}`. 
- Please report an issue to PyTorch.



[Back to Registry](../index.md)
