# GB0047

## Graph-Break Type
*Short name describing what triggered the graph break*
Encountered unconverted argument when attempting to inline

## Context
*Values or code snippet captured at the break point*
func: {func}, arg: {v}

## Explanation
*Why this specific graph break happened*
An argument to an inlined function was not successfully converted to a VariableTracker.

## Hints
*Suggestions for fixing or working around the break*
- This is likely to be a Dynamo bug. Please report an issue to PyTorch.



[Back to Registry](../index.md)
