# GB0132

## Graph-Break Type
*Short name describing what triggered the graph break*
Unsupported `func` in itertools.accumulate

## Context
*Values or code snippet captured at the break point*
call_function {self} {args} {kwargs}

## Explanation
*Why this specific graph break happened*
Dynamo does not know how to get the function to use for itertools.accumulate. itertools.accumulate expects the `func` as the second argument or as a keyword argument.

## Hints
*Suggestions for fixing or working around the break*
- Dynamo has detected that tracing the code will result in an error when running in eager. Please double check that your code doesn't contain a similar error when actually running eager/uncompiled.



[Back to Registry](../index.md)
