# GB0193

## Graph-Break Type
*Short name describing what triggered the graph break*
invalid call to builtin op handler

## Context
*Values or code snippet captured at the break point*
invalid args to {self_handler}: {args} {kwargs}

## Explanation
*Why this specific graph break happened*
Encountered TypeError when trying to handle op {fn.__name__}

## Hints
*Suggestions for fixing or working around the break*
- This graph break may be difficult to debug. Please report an issue to PyTorch for assistance.



[Back to Registry](../index.md)
