# GB0213

## Graph-Break Type
*Short name describing what triggered the graph break*
unimplemented builtin op on tensor arguments

## Context
*Values or code snippet captured at the break point*
partial tensor op: {self} {args} {kwargs}

## Explanation
*Why this specific graph break happened*
Dynamo does not know how to trace builtin operator {self.fn} with tensor arguments

## Hints
*Suggestions for fixing or working around the break*
- It may be possible to write Dynamo tracing rules for this code. Please report an issue to PyTorch if you encounter this graph break often and it is causing performance issues.



[Back to Registry](../index.md)
