---
layout: default
---
# GB0032

## Graph-Break Type
*Short name describing what triggered the graph break*

Custom __getattribute__ in nn.Module dict key check

## Context
*Values or code snippet captured at the break point*

has_key_in_generic_dict {self} {key}

## Explanation
*Explanation of why the graph break was triggered*

Dynamo does not support checking key existence on `nn.Module` instances that have a custom `__getattribute__` method defined.

## Hints
*Hints on how to resolve the graph break*

- Avoid defining `__getattribute__` in your module.
- It may be possible to write Dynamo tracing rules for this code. Please report an issue to PyTorch if you encounter this graph break often and it is causing performance issues.


## Additional Information

<!-- ADDITIONAL INFORMATION START - Add custom information below this line -->

<!-- ADDITIONAL INFORMATION END -->


[Click here to add Additional Info](https://github.com/meta-pytorch/compile-graph-break-site/edit/main/docs/gb/gb0032.md)

[Back to Registry](../index.html)
