---
layout: default
---
# GB0045

## Graph-Break Type
*Short name describing what triggered the graph break*

Encountered tensor.is_inference() during tracing

## Context
*Values or code snippet captured at the break point*



## Explanation
*Explanation of why the graph break was triggered*

tensor.is_inference() is not supported

## Hints
*Hints on how to resolve the graph break*

- This graph break is fundamental - it is unlikely that Dynamo will ever be able to trace through your code. Consider finding a workaround.


## Additional Information

<!-- ADDITIONAL INFORMATION START - Add custom information below this line -->

<!-- ADDITIONAL INFORMATION END -->

[Back to Registry](../index.html)

[Edit this page on GitHub](https://github.com/pytorch-labs/compile-graph-break-site/edit/main/docs/gb/gb0045.md)
