---
layout: default
---
# GB0046

## Graph-Break Type
*Short name describing what triggered the graph break*

Encountered torch.is_inference_mode_enabled during tracing

## Context
*Values or code snippet captured at the break point*



## Explanation
*Explanation of why the graph break was triggered*

torch.is_inference_mode_enabled() is not supported

## Hints
*Hints on how to resolve the graph break*

- This graph break is fundamental - it is unlikely that Dynamo will ever be able to trace through your code. Consider finding a workaround.


## Additional Information

<!-- ADDITIONAL INFORMATION START - Add custom information below this line -->

<!-- ADDITIONAL INFORMATION END -->

