---
layout: default
---
# GB0105

## Graph-Break Type
*Short name describing what triggered the graph break*

Tensor.numpy() with trace_numpy=False

## Context
*Values or code snippet captured at the break point*

call_method {self} numpy

## Explanation
*Explanation of why the graph break was triggered*

`Tensor.numpy()` was called, but the `trace_numpy` configuration was manually disabled.

## Hints
*Hints on how to resolve the graph break*

- Set `torch._dynamo.config.trace_numpy = True` to allow 
- Dynamo to trace through NumPy.


## Additional Information

<!-- ADDITIONAL INFORMATION START - Add custom information below this line -->

<!-- ADDITIONAL INFORMATION END -->

[Back to Registry](../index.html)
