---
layout: default
---
# GB0168

## Graph-Break Type
*Short name describing what triggered the graph break*

Variadic function call with bad flags

## Context
*Values or code snippet captured at the break point*

flags: {inst.argval}

## Explanation
*Explanation of why the graph break was triggered*

Attempted to call a variadic function (CALL_FUNCTION_EX) with bad flags {inst.argval}

## Hints
*Hints on how to resolve the graph break*

- This is likely to be a Dynamo bug. Please report an issue to PyTorch.


## Additional Information

<!-- ADDITIONAL INFORMATION START - Add custom information below this line -->

<!-- ADDITIONAL INFORMATION END -->


[Click here to add Additional Info](https://github.com/pytorch-labs/compile-graph-break-site/edit/main/docs/gb/gb0168.md)

[Back to Registry](../index.html)
