---
layout: default
---
# GB0124

## Graph-Break Type
*Short name describing what triggered the graph break*

Unsupported Tensor.item() call with capture_scalar_outputs=False

## Context
*Values or code snippet captured at the break point*

call_method {self} item {args} {kwargs}

## Explanation
*Explanation of why the graph break was triggered*

Dynamo does not support tracing `Tensor.item()` with config.capture_scalar_outputs=False.

## Hints
*Hints on how to resolve the graph break*

- Set `torch._dynamo.config.capture_scalar_outputs = True` 
- or `export TORCHDYNAMO_CAPTURE_SCALAR_OUTPUTS=1` 
- to include these operations in the captured graph.


## Additional Information

<!-- ADDITIONAL INFORMATION START - Add custom information below this line -->

<!-- ADDITIONAL INFORMATION END -->


[Click here to add Additional Info](https://github.com/pytorch-labs/compile-graph-break-site/edit/main/docs/gb/gb0124.md)

[Back to Registry](../index.html)
