---
layout: default
---
# GB0275

## Graph-Break Type
*Short name describing what triggered the graph break*

torch._dynamo.step_unsupported() with empty checkpoint

## Context
*Values or code snippet captured at the break point*



## Explanation
*Explanation of why the graph break was triggered*

traced torch._dynamo.step_unsupported(), but there is no checkpoint to step_graph_break from. This graph break is used for debugging only.

## Hints
*Hints on how to resolve the graph break*

- Remove the torch._dynamo.step_unsupported() call.
- Include at least one checkpoint: (1) include at least 2 ops and (2) make sure there is some 
- line of code that is not in a try/with block, and has an empty Python stack.
- This is likely to be a Dynamo bug. Please report an issue to PyTorch.


## Additional Information

<!-- ADDITIONAL INFORMATION START - Add custom information below this line -->

<!-- ADDITIONAL INFORMATION END -->


[Click here to add Additional Info](https://github.com/meta-pytorch/compile-graph-break-site/edit/main/docs/gb/gb0275.md)

[Back to Registry](../index.html)
