---
layout: default
---
# GB0255

## Graph-Break Type
*Short name describing what triggered the graph break*

attempted to call sourceless user-defined object as a method

## Context
*Values or code snippet captured at the break point*

object={self.value}, function={func}, args={args}, kwargs={kwargs}

## Explanation
*Explanation of why the graph break was triggered*

Dynamo does not support this.

## Hints
*Hints on how to resolve the graph break*

- Ensure the user-defined object {self.value} is constructed outside the compiled region.


## Additional Information

<!-- ADDITIONAL INFORMATION START - Add custom information below this line -->

<!-- ADDITIONAL INFORMATION END -->


[Click here to add Additional Info](https://github.com/meta-pytorch/compile-graph-break-site/edit/main/docs/gb/gb0255.md)

[Back to Registry](../index.html)
