# GB0079

## Graph-Break Type
*Short name describing what triggered the graph break*
Missing CALL_INTRINSIC_1 handler

## Context
*Values or code snippet captured at the break point*
CALL_INTRINSIC_1 operand: {inst.argval}

## Explanation
*Why this specific graph break happened*
No handler implemented for CALL_INTRINSIC_1 {inst.argval} instruction.

## Hints
*Suggestions for fixing or working around the break*
- It may be possible to write Dynamo tracing rules for this code. Please report an issue to PyTorch if you encounter this graph break often and it is causing performance issues.



[Back to Registry](../index.md)
